### ISSUE TITLE
Add simple presets support

### ISSUE THREAD

**Issue by sergeysova** [EvgenyiFedotov/swagger-to-js#14]
### Now

A library requires to write or copy/paste config for each new API or application.

### Proposal

Add the `presets` field, which should be npm package name or path to js file.

### Example

Preset `effector-swagger-to-js-preset`:
```js
// "main": "index.js",

module.exports = {
  importRequest: "disabled",
  templateCodeBefore: () => `import { requestFx } from '../request';`,
  templateRequestCode: generateMyRequestFx,
}
```

`.swagger-to-jsrc.yaml`:
```yaml
file: https://public.svc.company.com/project/api/swagger.yaml
outputDir: ./src/api/generated
presets:
  - effector-swagger-to-js-preset
```

### Use case

1. Allow easy to reuse templates for different projects
1. Allow using 2 or more templates simultaneously. For example template for source code and another template for types.

### Edge cases

1. Local properties always override properties from presets
1. If passed >1 templates, each next template merged with previous
